# Generated by Django 4.1 on 2025-04-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_add_restaurant_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='visitor_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
